// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrJtRART_dZvfGbQ7XIGXsa8KjPWXxqgM',
    appId: '1:900537069591:web:4b01d7719b4fc045766c52',
    messagingSenderId: '900537069591',
    projectId: 'tiktok-tutorial-5a3b6',
    authDomain: 'tiktok-tutorial-5a3b6.firebaseapp.com',
    databaseURL: 'https://tiktok-tutorial-5a3b6-default-rtdb.firebaseio.com',
    storageBucket: 'tiktok-tutorial-5a3b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClpWi97SzyCHRt-aUBpWa2yH5oVS70KjQ',
    appId: '1:900537069591:android:e7798de521cf1a13766c52',
    messagingSenderId: '900537069591',
    projectId: 'tiktok-tutorial-5a3b6',
    databaseURL: 'https://tiktok-tutorial-5a3b6-default-rtdb.firebaseio.com',
    storageBucket: 'tiktok-tutorial-5a3b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4BqTyIFgnkLz7DCO0_lp-LQ1B31q710w',
    appId: '1:900537069591:ios:3dce4d5fde760004766c52',
    messagingSenderId: '900537069591',
    projectId: 'tiktok-tutorial-5a3b6',
    databaseURL: 'https://tiktok-tutorial-5a3b6-default-rtdb.firebaseio.com',
    storageBucket: 'tiktok-tutorial-5a3b6.appspot.com',
    iosBundleId: 'com.example.tiktokTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4BqTyIFgnkLz7DCO0_lp-LQ1B31q710w',
    appId: '1:900537069591:ios:3dce4d5fde760004766c52',
    messagingSenderId: '900537069591',
    projectId: 'tiktok-tutorial-5a3b6',
    databaseURL: 'https://tiktok-tutorial-5a3b6-default-rtdb.firebaseio.com',
    storageBucket: 'tiktok-tutorial-5a3b6.appspot.com',
    iosBundleId: 'com.example.tiktokTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrJtRART_dZvfGbQ7XIGXsa8KjPWXxqgM',
    appId: '1:900537069591:web:1f93ba07b2219cc2766c52',
    messagingSenderId: '900537069591',
    projectId: 'tiktok-tutorial-5a3b6',
    authDomain: 'tiktok-tutorial-5a3b6.firebaseapp.com',
    databaseURL: 'https://tiktok-tutorial-5a3b6-default-rtdb.firebaseio.com',
    storageBucket: 'tiktok-tutorial-5a3b6.appspot.com',
  );
}
